[package]
name = "practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
serde = "1.0.197"
sysinfo = "0.30.7"
tokio = { version = "1.36.0", features = ["full"] }
